// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using CareerFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CareerFlowDbContext))]
    partial class CareerFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerFlow.Core.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Details")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "Action")
                        .HasDatabaseName("idx_activity_logs_action");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_activity_logs_user");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CertificateId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("certificate_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("credential_url");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issue_date");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("issuer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_certificates_person");

                    b.HasIndex("PersonId", "Issuer")
                        .HasDatabaseName("idx_certificates_issuer");

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("course");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("education_level");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Grade")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("grade");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Completed")
                        .HasColumnName("status");

                    b.Property<string>("ThesisTitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("thesis_title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_educations_person");

                    b.HasIndex("PersonId", "EducationLevel")
                        .HasDatabaseName("idx_educations_level");

                    b.HasIndex("PersonId", "IsCurrent")
                        .HasDatabaseName("idx_educations_current");

                    b.ToTable("educations", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Brasil")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("employment_type");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("position");

                    b.PrimitiveCollection<List<Guid>>("SkillsUsed")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skills_used");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_experiences_person");

                    b.HasIndex("PersonId", "IsCurrent")
                        .HasDatabaseName("idx_experiences_current");

                    b.HasIndex("PersonId", "StartDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_experiences_dates");

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsNative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_native");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("language_name");

                    b.Property<string>("ListeningLevel")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("listening_level");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("proficiency_level");

                    b.Property<string>("ReadingLevel")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("reading_level");

                    b.Property<string>("SpeakingLevel")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("speaking_level");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WritingLevel")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("writing_level");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_languages_person");

                    b.HasIndex("PersonId", "LanguageName")
                        .IsUnique()
                        .HasDatabaseName("idx_languages_unique");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentCompany")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("current_company");

                    b.Property<string>("CurrentPosition")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("current_position");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("Phone")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("ProfessionalSummary")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("professional_summary");

                    b.Property<string>("ResumeSlug")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("resume_slug");

                    b.Property<string>("State")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("idx_persons_public");

                    b.HasIndex("ResumeSlug")
                        .IsUnique()
                        .HasDatabaseName("idx_persons_slug")
                        .HasFilter("resume_slug IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_persons_user");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.ResumeAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("analyzed_at");

                    b.Property<int?>("AtsCompatibility")
                        .HasColumnType("integer")
                        .HasColumnName("ats_compatibility");

                    b.Property<string>("AtsIssues")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("ats_issues");

                    b.Property<int?>("AtsScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_score");

                    b.Property<string>("AtsSuggestions")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("ats_suggestions");

                    b.Property<int?>("AverageViewDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("average_view_duration_seconds");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DetectedKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("detected_keywords");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_viewed_at");

                    b.Property<string>("MissingKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_keywords");

                    b.Property<int>("PdfDownloads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pdf_downloads");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<int>("SharesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("shares_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<int>("TotalViews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_views");

                    b.Property<int>("UniqueViews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("unique_views");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_resume_analytics_person");

                    b.ToTable("resume_analytics", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.ResumeSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_applied");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("medium")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId", "IsApplied")
                        .HasDatabaseName("idx_resume_suggestions_person");

                    b.ToTable("resume_suggestions", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.ResumeView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("PdfDownloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pdf_downloaded");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("referrer");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int?>("ViewDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("view_duration_seconds");

                    b.Property<string>("ViewerCity")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("viewer_city");

                    b.Property<string>("ViewerCountry")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("viewer_country");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_resume_views_person");

                    b.HasIndex("PersonId", "Source")
                        .HasDatabaseName("idx_resume_views_source");

                    b.ToTable("resume_views", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("proficiency_level");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_skills_person");

                    b.HasIndex("PersonId", "Category")
                        .HasDatabaseName("idx_skills_category");

                    b.HasIndex("PersonId", "ProficiencyLevel")
                        .HasDatabaseName("idx_skills_level");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.SocialNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("NetworkType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("network_type");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_social_networks_person");

                    b.HasIndex("PersonId", "NetworkType")
                        .IsUnique()
                        .HasDatabaseName("idx_social_networks_unique");

                    b.ToTable("social_networks", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_premium");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastPasswordChangeAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_password_change_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NotificationPreferences")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("notification_preferences");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PremiumUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("premium_until");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<string>("ThemePreferences")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("theme_preferences");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("two_factor_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_login")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Email"), new[] { "Id", "PasswordHash", "IsActive", "LockedUntil" });

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_users_role");

                    b.HasIndex("IsPremium", "PremiumUntil")
                        .HasDatabaseName("idx_users_premium");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("error_stack_trace");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("headers");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_retries");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_created");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_outbox_type");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_pending")
                        .HasFilter("status = 'pending'");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.ActivityLog", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Certificate", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("Certificates")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Education", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("Educations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Experience", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("Experiences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Language", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("Languages")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Person", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("CareerFlow.Core.Entities.Person", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.ResumeAnalytics", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithOne("ResumeAnalytics")
                        .HasForeignKey("CareerFlow.Core.Entities.ResumeAnalytics", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.ResumeSuggestion", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("ResumeSuggestions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.ResumeView", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("ResumeViews")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Skill", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("Skills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.SocialNetwork", b =>
                {
                    b.HasOne("CareerFlow.Core.Entities.Person", "Person")
                        .WithMany("SocialNetworks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.Person", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Languages");

                    b.Navigation("ResumeAnalytics");

                    b.Navigation("ResumeSuggestions");

                    b.Navigation("ResumeViews");

                    b.Navigation("Skills");

                    b.Navigation("SocialNetworks");
                });

            modelBuilder.Entity("CareerFlow.Core.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
